# Example Skill Data config
Rogue:
  Basic:
    - "Stroke"
    - "Sprint"
    - "Archery"
    - "Stab"
    - "Stab2"
    - "Archery2"
    - "Swift"
    - "Strength of Wolf"
  Archery:
    - "Through Shot"
    - "Fire Arrow"
    - "Poison Arrow"
    - "Multiple shot"
    - "Guided Arrow"
    - "Perfect Shot"
    - "Fire Shot"
    - "Poison Shot"
    - "Arc Shot"
    - "Explosive Shot"
    - "Viper"
    - "Arrow Shower"
    - "Shadow Hunter"
    - "Dark Pursuer"
    - "Blow Arrow"
    - "Strafe"
    - "Power Shot"
  Assassinate:
    - "Jab"
    - "Blood Drain"
    - "Pierce"
    - "Shock"
    - "Illusion"
    - "Thrust"
    - "Cut"
    - "Stealth"
    - "Vampiric Touch"
    - "Spike"
    - "Bloody Beast"
    - "Critical Point"
    - "Blinding"
    - "Beast Hiding"
  Search:
    - "Hide"
    - "Minor Healing"
    - "Evade"
    - "Cats Eyes"
    - "Light Feet"
    - "Safety"
    - "Lupine Eyes"
    - "Cure Curse"
    - "Cure Disease"
    - "Scaled Skin"
    - "Wild Advent"
    - "Enhanced Concentration"
    - "Smoke Screen"
  Master:
    - "Magic Shield"
    - "Source Masking"
    - "Disarm"

# You can add more class skill data for Mage, Priest, Warrior similarly
