name: Python Lint flake mypy and isort

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:

jobs:
  check_base:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Check if changed files include python files
      uses: technote-space/get-diff-action@v6
      with:
        DIFF_FILTER: 'ACDMRTUXB' # https://git-scm.com/docs/git-diff
        PATTERNS: |
          **.py
          **/*.py
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy isort pytest

    - name: Lint with flake8
      run: |
        # E402: module level import not at top of file
        flake8 . --count --statistics --ignore=E402 --max-line-length 120

    - name: Type checking with mypy
      run: |
        mypy . --ignore-missing-imports

    - name: Sort check with isort
      run: |
        isort . --diff
        isort . --check-only